#!/usr/bin/env bash
echo "== put object"

set -e  # Exit the script if any command fails

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "There needs to be a filename eg. ./bucket my-bucket-name my-filename"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
FILE_EXTENSION=$(basename "$FILENAME")

# https://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html
aws s3api put-object \
--bucket "$BUCKET_NAME" \
--body "$FILENAME" \
--key "$FILE_EXTENSION"